### ISSUE TITLE
SparkContext's app name should control which spark kernel to connect to.

### ISSUE THREAD

**Issue by bpburns** [EclairJS/eclairjs-node#20]
The jupyter notebook protocol does not allow us to control kernel id's when a new kernel is requested, therefore we need something to bind SparkContext's app name to kernel id.  The /api/sessions endpoint allows us to create a session with a notebook path.  The notebook path can be used to store the app name.  Here is what should happen when a SparkContext is created.

1. Get a list of all the notebook sessions.  Do any of these sessions contain a notebook path that match our app name?

2. Yes. Return a reference to that kernel and it's SparkContext variable.

3. No. Create a new session with the app name as the notebook path, this will in turn create a new kernel.

The node developer can share SparkContexts across instances by using the same app name for all instances.  If the developer wishes to have a unique SparkContext across applications instances than he/she should make sure unique app names are generated when creating a new SparkContext.

**Comment by bpburns** [comment]
Make sure we create a branch to do this work, as /api/sessions is not implemented in the kernel gateway so we'll have to use the full notebook server.  When /api/sessions is implemented can we close this issue and merge into master

**Comment by doronrosenberg** [comment]
Created a branch (https://github.com/EclairJS/eclairjs-node/tree/sessionmanagement) for this.

**Comment by doronrosenberg** [comment]
I am still unsure about using SparkContext.stop() to kill the kernel since you can stop and then start a SparkContext.  Killing the kernel during stop() would break that chain I believe.

**Comment by doronrosenberg** [comment]
Checked in SparkContext.stop() for killing the Kernel.  Once I stop() a program, the next time I try to run it (using the same app name) I get:

```
[E 14:28:14.943 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/Users/doronrosenberg/mystuff/ibm/eclairjs/notebook/notebook/notebook/base/handlers.py", line 459, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/Users/doronrosenberg/mystuff/ibm/eclairjs/notebook/notebook/notebook/services/sessions/handlers.py", line 53, in post
        model = sm.get_session(path=path)
      File "/Users/doronrosenberg/mystuff/ibm/eclairjs/notebook/notebook/notebook/services/sessions/sessionmanager.py", line 139, in get_session
        return self.row_to_model(row)
      File "/Users/doronrosenberg/mystuff/ibm/eclairjs/notebook/notebook/notebook/services/sessions/sessionmanager.py", line 178, in row_to_model
        raise KeyError
    KeyError
[E 14:28:14.944 NotebookApp] {
      "Content-Length": "54",
      "Connection": "close",
      "Accept": "*/*",
      "User-Agent": "node-XMLHttpRequest",
      "Host": "127.0.0.1:8888",
      "Content-Type": "application/json"
    }
[E 14:28:14.944 NotebookApp] 500 POST /api/sessions?1453328894930 (127.0.0.1) 1.17ms referer=None
```
The next run though will work as normal.  Only happens on reusing the Notebook path name.

**Comment by bpburns** [comment]
How are you deleting the kernel?  Are you stopping the session as well?

**Comment by doronrosenberg** [comment]
@bpburns I am only stopping the kernel, I guess I need to kill the session as well? Is there a specific order I should kill them in?

**Comment by doronrosenberg** [comment]
Looks like killing the session will kill the kernel but not vice versa.
