### ISSUE TITLE
Spark Summit Airports / Delayed Flights example Apllication

### ISSUE THREAD

**Issue by danielsan** [EclairJS/eclairjs-node#42]
At the last spark summit you were showing on application displaying all the airports in the US and the percentage of delayed flights.

That is a great use case and may be very useful to learn how you guys use the eclairjs in a real app.

Is that application available? Is that open source?

**Comment by jtbarbetta** [comment]
I have added the airline demo under the examples [here](https://github.com/EclairJS/eclairjs-node/tree/master/examples/airline).  The README hopefully has what you need to get up and running with it.  Please let me know if you have any problems getting it running.

**Comment by jtbarbetta** [comment]
Closing this as demo is now in public repository.
