### ISSUE TITLE
Update existing code to use Utils.js methods for code generation

### ISSUE THREAD

**Issue by doronrosenberg** [EclairJS/eclairjs-node#7]

**Comment by jtbarbetta** [comment]
For the new SqlDate and SqlTimestamp classes I added I made sure I was using the Utils.js methods for code generation.  I will update Row.js as well tomorrow.

**Comment by jtbarbetta** [comment]
Finished Row.js.

**Comment by doronrosenberg** [comment]
The only remaining fils are DStream and KafkaUtils
