### ISSUE TITLE
Wiki Instructions use wrong Git Clone URL

### ISSUE THREAD

**Issue by whereswaldon** [EclairJS/eclairjs-node#96]
On [this page](https://github.com/EclairJS/eclairjs-node/wiki/Using-the-Docker-Container), the wiki tells you to clone from the wrong URL (in the instructions at the bottom). The repository has been moved since then. It needs to be cloning from `https://github.com/EclairJS/eclairjs-node`. I would have made a PR, but I couldn't figure out how to fork a wiki.

**Comment by whereswaldon** [comment]
Also, for me, `node --harmony examples/rddtop10.js` fails because it can't find the data file `dream.txt`. However, `cd examples; node rddtop10.js dream.txt` does work.

**Comment by doronrosenberg** [comment]
Fixed
