### ISSUE TITLE
0.4 Release Typo

### ISSUE THREAD

**Issue by whereswaldon** [EclairJS/eclairjs-node#97]
In `eclairjs-node/lib/sql/types/module.js`, there are two references to MetaData.js, but the file is actually called Metadata.js. This has been fixed by later commits, but it would be awesome if a 0.4.1 could be released with this fixed.

**Comment by bpburns** [comment]
We are just releasing a 0.5 version of eclairjs-nashorn and eclairjs-node
will follow.

On Wed, Jun 8, 2016 at 7:24 AM, Christopher Waldon <notifications@github.com

**Comment by doronrosenberg** [comment]
0.5 is out on npm
