### ISSUE TITLE
Promises returned from action methods should return in memory versions of Spark Objects

### ISSUE THREAD

**Issue by bpburns** [EclairJS/eclairjs-node#99]
Currenty given a DataFrame, the invocation of a take, or collect returns a Promise that resolves to an Array of Row objects.  Those Row objects are remote references to objects in eclairjs-nashorn.  Therefore any calls to the values in those row objects result in another Promise being returned.  Instead the Row objects should contain all the values locally and not require another callback to eclairjs-nashorn.  This is not unreasonable as takes, collects, head, etc. are action requests anyway.

The same should be true action requests on RDD's.

**Comment by doronrosenberg** [comment]
Looking at DataFrames, right now DataFrame.take() returns an array of json and not Rows, so that would change I assume?

The tricky part is if Rows can now be local, we have to handle them being used again in spark, which should be doable.

With RDDs things get a bit more complicated:

```javascript
    var  rdd = sc.parallelize([
      spark.sql.RowFactory.create(spark.mllib.linalg.Vectors.sparse(3, [0, 1], [-2.0, 2.3])),
      spark.sql.RowFactory.create(spark.mllib.linalg.Vectors.dense([-2.0, 2.3, 0.0]))
    ]);

  rdd.collect();
```
We actually fail here in nashorn as there is no toJSON on Vectors, but if we are creating these rows locally we would need to support all the possible RDD types locally (like Vectors) right?

**Comment by bpburns** [comment]
In eclairjs-nashorn DataFrame.take does the right thing and returns an
array of Row objects.  It comes back as json in eclairjs-node because we
end up calling toString on all the Row objects.  We should have enough
information within that json to recreate the Row object on the
eclairjs-node side.

The example of using RowFactory.create with Vectors is a fringe case but
it's valid.  I think > 80% of the time we are using spark objects like
Vectors, Rows, RowFactory in lambda functions where they are executing in
nashorn. We need think about all the case where it makes more sense to use
in memory objects in eclairjs-node rather remote references.  I would think
in the above example we would want to keep these all in memory on the node
side until the actual call to sc.parallelize gets invoked.  So yes we would
need support all of those types.

**Comment by doronrosenberg** [comment]
First step will be to move DataFrame over to use local rows.  Row will still return a promise for everything for now since we have to support both behaviors and will switch to directly returning values once we got everything converted.

**Comment by doronrosenberg** [comment]
Work is being done in https://github.com/EclairJS/eclairjs-node/tree/in-memory-rows

**Comment by doronrosenberg** [comment]
I merged the branch into master - Row objects returned by DataFrame.collect/take now are cached locally.  If they get send back to Nashorn we create them then as needed.

**Comment by doronrosenberg** [comment]
Master now has Rows that return values directly instead of promises
